Sprint_01/D2D_project/D2D_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('bookstore/', include('test_bookstore.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Sprint_01/D2D_project/test_bookstore/urls.py
from django.urls import include, path
from .views import FileView
from .views import ProcessXML
from . import views
from django.conf.urls import url


app_name = 'test_bookstore'
urlpatterns = [
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('upload/', FileView.as_view(), name='file-upload'),
    path('process/', ProcessXML.as_view(), name='file-process'),
    # Put the page URL's individually for the thing.
    path('', views.search, name='search'),
    path('<int:pk>/details', views.bookDetail.as_view(), name='book_detail'),
]

Sprint_01/D2D_project/test_bookstore/models.py
from django.db import models
import os

# Create your models here.
class Book(models.Model):
    ISBN = models.CharField(max_length=13, primary_key=True)
    title = models.CharField(max_length=200)
    primary_author = models.CharField(max_length=100)
    secondary_authors = models.CharField(max_length=200, default=None, blank=True, null=True)
    description = models.TextField()
    publisher = models.CharField(max_length=200)
    release_date = models.CharField(max_length=15)
    price = models.CharField(max_length=50)
    series = models.CharField(max_length=200, default=None, blank=True, null=True)
    volume_number = models.CharField(max_length=10, default=None, blank=True, null=True)
    is_available = models.BooleanField(default=False)

    def __str__(self):
        return f' {self.ISBN}, {self.title}, {self.primary_author}, {self.secondary_authors}'
        
def user_directory_path(instance, filename): 
    path = 'media/'
    if os.path.exists('media/onix3.xml'):
        os.remove('media/onix3.xml')
    
    filename = "onix3.xml"
    
    return "onix3.xml"
  
class File(models.Model):
    f = models.FileField(blank=False, null=False, upload_to = user_directory_path)
    timestamp = models.DateTimeField(auto_now_add=True)
    

Sprint_01/D2D_project/test_bookstore/forms.py
from django import forms


"""
args:
    a DjangoForm form: This is our constructor for creating
    the form that will serve as our search bar.
returns:
    not applicable
synopsis:
    A simple search bar that will be what the user uses to
    query the database for books.
"""
class searchBar(forms.Form):
    searcher = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class' : 'searchBar'}))

Sprint_01/D2D_project/test_bookstore/views.py
from django.shortcuts import render, get_object_or_404

from django.template import loader, RequestContext
from django.views import generic

from django_tables2.config import RequestConfig

# Create your views here.
from rest_framework import viewsets

from .serializers import BookSerializer
from .models import Book

from rest_framework.views import APIView
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.response import Response
from rest_framework import status
from .serializers import FileSerializer
from .onix_parse import parseXML

from .models import File
import os

from .models import Book
from .tables import ResultsTable
from .forms import searchBar

from .search import Search_Query


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('title')
    serializer_class = BookSerializer

class FileView(APIView):
    parser_classes = (MultiPartParser, FormParser)
    
    def post(self, request, *args, **kwargs):
        file_serializer = FileSerializer(data=request.data)
        if file_serializer.is_valid():
            file_serializer.save()
            return Response(file_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProcessXML(APIView):
    parser_classes = (MultiPartParser, FormParser)
    
    def post(self, request, *args, **kwargs):

        if (parseXML('media/onix3.xml')==1):
            return Response(status.HTTP_201_CREATED)
        else:
            return Response(status.HTTP_400_BAD_REQUEST)



"""
args:
    Http request: Requests from either POST or GET. Will
    be used for list display, searcher, and to paginate.
returns:
    An Http Render: A render of the Search Bar Form and
    Results Table to be displayed in "search.html"
synopsis:
    The view serves as the search page as well as listing
    the search results from the query made. It will also
    provide options to visit each individual entry with a
    "details" link. It will contain all the books from the
    database and list them accordingly with no cut off point,
    though one could be implemented in the future.
"""
def search(request):

    # empty list that will hold our search display data for
    # the ResultsTable    
    results_display = []
    results = ""
    # POST forcer for our "page" GET request. So we can
    # access our old POST data when we move to the next page.
    if not request.method == 'POST' and 'page' in request.GET:
        if 'searcher' in request.session:
            request.POST = request.session['searcher']
            request.method = 'POST'

    
    if request.method == 'POST':

        # Acquiring the user's input on the search bar
        form = searchBar(request.POST)
        request.session['searcher'] = request.POST

        # checking data and using it for our Search_Query function.
        if form.is_valid():

            searcher = form.cleaned_data['searcher']

            # Receiving results in a list of [Book Object, float]
            results = Search_Query(searcher)


            # Loop for constructing the list of dictionaries to build our ResultsTable
            for books in results:
                if float(books[1])> float(0) and getattr(books[0], "is_available"):
                    dicts = {}
                    dicts["title"] = getattr(books[0], "title")
                    dicts["author"] = getattr(books[0], "primary_author")
                    dicts["ISBN"] = getattr(books[0], "ISBN")
                    dicts["rating"] = books[1]
                    results_display.append(dicts)            
    else:
        # Purposes of hiding the list until a query is made.
        form = searchBar()

    # Building our Results Table from the list of dictionary data.
    # and creating the paginator for the results.
    results_table = ResultsTable(results_display)
    RequestConfig(request, paginate={"per_page": 10}).configure(results_table)

    context = {
        'table': results_table,
        'results': results,
        'form': form,
    }

    return render(request, 'test_bookstore/search.html', context=context)


"""
args:
    generic Detail View: for creating the Book Detail class view
returns:
    not applicable
synopsis:
    This is the class that will allow direct mapping to our
    database for displaying book details in the book detail
    view. This will simplify the connections and it's primary
    function will be responsible for location and passing in the
    render.
"""
class bookDetail(generic.DetailView):
    model = Book

    """
    args:
        Http request: to acquire the request from the browser to
        open the page.
        primary key: This will be the key we use to locate the
        specific book in the database that the user was wanting to
        see the details about.
    returns:
        An Http Render: This render will be for our book data's context
        as well as directing to the 'book_detail.html' file.
    synopsis:
        This is our other page whose purpose is to display the
        various bits of information about books from the database.
        To reach this page, a user must click on the "details" link
        from their queries and will be brought to the details page with
        all the book data displayed accordingly.
    """
    def detail(self, request, primary_key):

        book = get_object_or_404(Book, pk=primary_key)

        context = {
            'book': book
            }

        return render(request, 'test_bookstore/book_detail.html', context=context)

Sprint_01/D2D_project/test_bookstore/templates/test_bookstore/book_detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'test_bookstore/detail_page_style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Big Shoulders Text' rel='stylesheet'>
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Georgia, 'Times New Roman', Times, serif;
}

/* Style the header */
.header {
  grid-area: header;
  padding: 10px;
  text-align: center;
  font-size: 12px;
}

/* The grid container */
.grid-container {
  display: grid;
  grid-template-areas: 
    'header header header header header header' 
    'left middle middle middle middle right' 
    'footer footer footer footer footer footer';
  /* grid-column-gap: 10px; - if you want gap between the columns */
} 

.left,
.middle {
  padding: 10px;
  width: auto;
  height: auto; /* Should be removed. Only for demonstration */
}
.right {
  padding: 10px;
  width: 500px;
  height: auto; /* Should be removed. Only for demonstration */
}

/* Style the left column */
.left {
  grid-area: left;
}

/* Style the middle column */
.middle {
  grid-area: middle;
}

/* Style the right column */
.right {
  grid-area: right;
}

/* Style the footer */
.footer {
  grid-area: footer;
  background-color: #f1f1f1;
  padding: 10px;
  text-align: center;
}
.bookTitle {
    font-family: 'Big Shoulders Text';
    align-self: left;
    font-size: 40px;
}
.bookDetailHeading {
    font-family: 'Big Shoulders Text';
    align-self: left;
    font-size: 25px;
    font-weight: bold;
}
.bookDetail {
    font-family: Georgia, 'Times New Roman', Times, serif;
    align-self: left;
    font-size: 25px;
    font-weight: normal;

}
th, td {
  padding: 15px;
  text-align: left;
}
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #f4511e;
  border: none;
  color: #FFFFFF;
  text-align: center;
  font-size: 20px;
  padding: 12px;
  width: 120px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
  align-self: left;
  font-family: 'Big Shoulders Text';
}
.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00ab';
  position: absolute;
  opacity: 0;
  top: 0;
  left: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-left: 25px;
}

.button:hover span:after {
  opacity: 1;
  left: 0;
}

/* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
  .grid-container  {
    grid-template-areas: 
      'header header header header header header' 
      'left left left left left left' 
      'middle middle middle middle middle middle' 
      'right right right right right right' 
      'footer footer footer footer footer footer';
  }

}
</style>
</head>
<body>
<div class="grid-container">
  <div class="header" >
    <p style="font-size: 2.4em; color:#f4511e;" align="right"><img src="https://draft2digital-prod-static.s3.amazonaws.com/img/outer/d2d-logo-dark-xs.png" alt="Company Icon" align="center"width="100" height="60">  Test Bookstore</p>
  </div>
  
  <div class="left">
    <a class="button" onClick="javascript:history.go(-1);" style="vertical-align:middle"><span>Back</span></a>  
  </div>
  <div class="middle" style="background-color: whitesmoke;">
    <p class="bookTitle"><b>{{ book.title }}</b></p>
    <table id="dataTable">
        <tr>
            <td class="bookDetailHeading">Author:</td>
            <td class="bookDetail">{{ book.primary_author }}
              {% if book.secondary_authors != "None" %}
               , {{ book.secondary_authors }}
              {%endif%}
            </td>
        </tr>
        <tr>
            <td class="bookDetailHeading">ISBN 13#:</td>
            <td class="bookDetail">{{ book.ISBN }}</td>
        </tr>
        <tr>
            <td class="bookDetailHeading">Publisher:</td>
            <td class="bookDetail">{{ book.publisher }}</td>
        </tr>
        <tr>
            <td class="bookDetailHeading">Release Date:  </td>
            <td class="bookDetail">{{ book.release_date }}</td>
        </tr>
        <tr>
            <td class="bookDetailHeading">Price:</td>
            <td class="bookDetail">{{ book.price }}</td>
        </tr>
        <tr>
            <td class="bookDetailHeading">Series:</td>
            <td class="bookDetail">{{ book.series }}</td>
        </tr>
        <tr>
            <td class="bookDetailHeading">Volume#:</td>
            <td class="bookDetail">{{ book.volume_number }}</td>
        </tr>
    </table>
  </div>  

  <div class="right" style = "background-color: #ccc;">
    <p class="bookDetailHeading">About Book:</p>
    <p class="bookDetail">{{ book.description|safe }}</p>
  </div>
  

</div>

</body>
</html>

Sprint_01/D2D_project/test_bookstore/templates/test_bookstore/search.html
<!DOCTYPE html>
{% load static %}
{% load django_tables2 %}
<html>

    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'test_bookstore/search_page_style.css' %}">
        <style>
        table{
            background-color:white;
            margin-left: auto;
            margin-right: auto;
            padding: 10px;
            width: 80%;
            font-size: 120%;
            border-bottom: 1px solid black;
            align-items:left;
        }
        th, td {
             padding: 15px;
             border-bottom: 1px solid black;
             text-align: left;
        }

        .center .form {
            border-radius: 25px;
            padding: 20px; 
            margin-left: auto;
            margin-right: auto;
            align-items: center;
            font-size: 120%;
      
        }

        .icon {
            margin-left: auto;
            margin-right: auto;
            width: 30%;
            font-size: 120%;
        }
        input[type=text] {
            border: none;
            border-radius: 8px;
            font-size: 100%;
            padding: 2px;

        }
        input[type=submit] {
            border-radius: 8px;
            background-color: #f4511e;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 16px;
            padding: 10px 8px;

        }
        .pagination {
            display: inline-block;
            align-items: center;
            margin-left: 10%;
        }

        .pagination a {
            color: whitesmoke;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            align-self: center;
        }

        .pagination a.active {
            background-color: #4CAF50;
            color: white;
            border-radius: 5px;
        }

        .pagination a:hover:not(.active) {
            background-color:#f4511e;
            border-radius: 5px;
        }
        ul li{
            display: inline;
            align-items: center;
        }

        * {
             box-sizing: border-box;
        }
        /* Style the header */
        .header {
            grid-area: header;
            text-align: center;
            font-size: 15px;
        }

        /* The grid container */
        .grid-container {
            display: grid;
            grid-template-areas: 
                'header header header header header header' 
                'middle middle middle middle middle middle';

        } 
        .middle {
            height: 100%; /* Should be removed. Only for demonstration */
        }
        /* Style the middle column */
        .middle {
            grid-area: middle;
        }
        /* Responsive layout - makes the three columns stack on top of each other instead of next to each other */
        @media (max-width: 600px) {
        .grid-container  {
            grid-template-areas: 
                'header header header header header header'  
                'middle middle middle middle middle middle';
        }
        }

        </style>
    </head>
    
    <body>
    <div class="grid-container">
        <div class="header">
    
            {% block logo %}
            <div class="icon" style="position:relative">     
                <p style="font-size: 2.4em; color:whitesmoke;" align="center"><img src="https://draft2digital-prod-static.s3.amazonaws.com/img/outer/d2d-logo-dark-xs.png" alt="Company Icon" align="center"width="100" height="60">  Test Bookstore</p>
            </div>
            {% endblock logo %}

        </div>
        <div class="middle">
            {% block searcher %}
            <div class="center">
                <form action="{% url 'test_bookstore:search' %}" method="post" class="form">
                
                    {{ form }}
                    {% csrf_token %}
                    <input type="submit" value="Search" id="searchButton">
                </form>
            </div>
            {% endblock searcher %}
            <div>
                {% if "" not in results %}
                    {% block table %}
                        {% render_table table %}
                    {% endblock table %}
                {% endif %}
            </div>
        </div>
    </div>
    </body>
</html>